# Generated by Django 5.1.6 on 2025-03-17 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texnomart', '0003_user_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
